package main;

import java.sql.*;
import javax.swing.JOptionPane;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;

public class TambahFrame extends javax.swing.JFrame {

    // variabel untuk melakukan query ke database
    private PreparedStatement pst;
    private final KoneksiToDatabase koneksi = new KoneksiToDatabase();

    public TambahFrame() {
        initComponents();
        // mengubah icon pada frame
        setIconImage(new ImageIcon("src/image/sepeda.png").getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jenisSepeda = new javax.swing.ButtonGroup();
        panel_utama = new javax.swing.JPanel();
        radioBtn_gowes = new javax.swing.JRadioButton();
        radioBtn_listrik = new javax.swing.JRadioButton();
        label_jenisSepeda = new javax.swing.JLabel();
        inputTipe = new javax.swing.JTextField();
        inputMerk = new javax.swing.JTextField();
        inputFitur1 = new javax.swing.JTextField();
        inputFitur2 = new javax.swing.JTextField();
        label_masukanDataSepeda = new javax.swing.JLabel();
        inputHarga = new javax.swing.JSpinner();
        inputStok = new javax.swing.JSpinner();
        btn_simpan = new javax.swing.JButton();
        btn_batal = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(730, 425));

        panel_utama.setBackground(new java.awt.Color(255, 204, 204));
        panel_utama.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));

        jenisSepeda.add(radioBtn_gowes);
        radioBtn_gowes.setSelected(true);
        radioBtn_gowes.setText("Sepeda Gowes");
        radioBtn_gowes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtn_gowesActionPerformed(evt);
            }
        });

        jenisSepeda.add(radioBtn_listrik);
        radioBtn_listrik.setText("Sepeda Listrik");
        radioBtn_listrik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioBtn_listrikActionPerformed(evt);
            }
        });

        label_jenisSepeda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_jenisSepeda.setText("Pilih Jenis Sepeda");

        inputTipe.setBorder(javax.swing.BorderFactory.createTitledBorder("Tipe"));
        inputTipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputTipeActionPerformed(evt);
            }
        });

        inputMerk.setBorder(javax.swing.BorderFactory.createTitledBorder("Merk"));

        inputFitur1.setBorder(javax.swing.BorderFactory.createTitledBorder("Jenis"));

        inputFitur2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ban"));

        label_masukanDataSepeda.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_masukanDataSepeda.setText("Masukan data sepeda");

        inputHarga.setBorder(javax.swing.BorderFactory.createTitledBorder("Harga"));

        inputStok.setBorder(javax.swing.BorderFactory.createTitledBorder("Stok"));

        btn_simpan.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        btn_batal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_batal.setText("Batal");
        btn_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_batalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_utamaLayout = new javax.swing.GroupLayout(panel_utama);
        panel_utama.setLayout(panel_utamaLayout);
        panel_utamaLayout.setHorizontalGroup(
            panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_utamaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_batal, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(inputMerk, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                            .addComponent(inputTipe))
                        .addComponent(inputHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(label_jenisSepeda)
                        .addGroup(panel_utamaLayout.createSequentialGroup()
                            .addComponent(radioBtn_gowes)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(radioBtn_listrik))
                        .addComponent(label_masukanDataSepeda)))
                .addGap(31, 31, 31)
                .addGroup(panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(inputFitur2, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)
                        .addComponent(inputFitur1))
                    .addComponent(inputStok, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        panel_utamaLayout.setVerticalGroup(
            panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_utamaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(inputStok, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_utamaLayout.createSequentialGroup()
                        .addComponent(label_jenisSepeda)
                        .addGap(1, 1, 1)
                        .addGroup(panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(radioBtn_gowes)
                            .addComponent(radioBtn_listrik))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_masukanDataSepeda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(inputTipe, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputMerk, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputFitur1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputHarga, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputFitur2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_utamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_simpan, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(btn_batal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        panel_utama.getAccessibleContext().setAccessibleName("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inputTipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputTipeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputTipeActionPerformed

    private void radioBtn_listrikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtn_listrikActionPerformed
        if (radioBtn_listrik.isSelected()) {
            inputFitur1.setBorder(javax.swing.BorderFactory.createTitledBorder("Kecepatan [km/h]"));
            inputFitur2.setBorder(javax.swing.BorderFactory.createTitledBorder("Baterai [V]"));
        }
    }//GEN-LAST:event_radioBtn_listrikActionPerformed

    private void radioBtn_gowesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioBtn_gowesActionPerformed
        if (radioBtn_gowes.isSelected()) {
            inputFitur1.setBorder(javax.swing.BorderFactory.createTitledBorder("Jenis"));
            inputFitur2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ban"));
        }
    }//GEN-LAST:event_radioBtn_gowesActionPerformed

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        // Pengecekan jika ada input yang kosong atau 0
        if (!inputTipe.getText().isEmpty() && !inputHarga.getValue().equals(0) && !inputMerk.getText().isEmpty()) {
            if (!inputStok.getValue().equals(0) && !inputFitur1.getText().isEmpty() && !inputFitur2.getText().isEmpty()) {
                try {
                    String sql = "INSERT INTO sepeda_gowes (tipe,merk,harga,stok,jenis,ban) VALUES ('%s','%s',%d,%d,'%s','%s')";
                    // jika dipilih sepeda listrik maka kita ubah kategorinya
                    if (radioBtn_listrik.isSelected()) {
                        sql = "INSERT INTO sepeda_listrik (tipe,merk,harga,stok,kecepatan,baterai) VALUES ('%s','%s',%d,%d,'%s','%s')";
                    }
                    // string format : memasukan data ke dalam string
                    // %s : untuk data bertipe string
                    // %d : untuk data bertipe int
                    // %f : untuk data bertipe float / double
                    sql = String.format(sql, inputTipe.getText(), inputMerk.getText(), inputHarga.getValue(),
                            inputStok.getValue(), inputFitur1.getText(), inputFitur2.getText());
                    Connection cn = koneksi.getKoneksi();
                    pst = cn.prepareStatement(sql);
                    pst.execute();
                    JOptionPane.showMessageDialog(panel_utama, "Tambah data berhasil");
                    MainFrame main = new MainFrame();
                    main.setVisible(true);
                    this.dispose();
                    return;
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(panel_utama, "Gagal membuat data baru : " + ex);
                } finally {
                    try {
                        pst.close(); // menutup statement yang sudah dijalankan
                    } catch (SQLException ex) {
                        Logger.getLogger(MainFrame.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        }
        // jika ada input yang kosong
        JOptionPane.showMessageDialog(panel_utama, "Input tidak boleh kosong / bernilai 0");
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void btn_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_batalActionPerformed
        MainFrame main = new MainFrame();
        main.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_batalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TambahFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TambahFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TambahFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TambahFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TambahFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_batal;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JTextField inputFitur1;
    private javax.swing.JTextField inputFitur2;
    private javax.swing.JSpinner inputHarga;
    private javax.swing.JTextField inputMerk;
    private javax.swing.JSpinner inputStok;
    private javax.swing.JTextField inputTipe;
    private javax.swing.ButtonGroup jenisSepeda;
    private javax.swing.JLabel label_jenisSepeda;
    private javax.swing.JLabel label_masukanDataSepeda;
    private javax.swing.JPanel panel_utama;
    private javax.swing.JRadioButton radioBtn_gowes;
    private javax.swing.JRadioButton radioBtn_listrik;
    // End of variables declaration//GEN-END:variables
}
